### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by ghost**
This adds Windows support by using the `libraylib_shared.dll`. I can successfully compile [core_basic_window.nim](https://github.com/define-private-public/raylib-Nim/blob/devel/examples/core_basic_window.nim). But in [bunnymark.nim](https://github.com/define-private-public/raylib-Nim/blob/devel/examples/bunnymark.nim) I get 2 warnings.
```
WARNING: [resources/wabbit_alpha.png] Image could not be loaded
WARNING: Texture could not be created
```
But I think that's because this binding is a bit outdated.

### CODE REVIEW

**Comment by define-private-public** [comment]
I haven't touched this stuff in a while, as I've been busy with other stuff.  And IIRC, there was some really odd issue where sprites were not displaying (some sort of Null mismatch issue, i think).  My brain is a bit fuzzy on the details.

I don't have much interest in working on this binding right now.  Do you want to take this over?  I can provide help for testing on Linux and OS X.

**Comment by ghost** [comment]
Yea I can understand that you aren't really interesting in the binding anymore after such a long time.

I'm actually new to Nim but I really like the syntax and the compile times so yes I guess I will try to get this binding up to date and fix this weird Null mismatch issue. I can already test Linux because of the Linux Subsystem for Windows 10. But i'm not sure how I should test OS X. Can you give me a hint?

**Comment by define-private-public** [comment]
For testing on OS X, do you have a machine running OS X somewhere?  Testing this should be the same as any other platform.

If you need any help with Nim, feel free to reach out.

**Comment by ghost** [comment]
No I don't have any machine running OS X. But I don't think thats a big problem.

Thanks! So I will work on the fork now.

**Comment by define-private-public** [comment]
Okay, good to hear.  If you want/need me to do any OS X testing (or Linux testing), feel free to reach out.

**Comment by define-private-public** [comment]
Or help with binding things to Nim for any matter.  IIRC, there were some others in the Nim community who were interested in a Nim bindings of raylib.

**Pull request closed without merging**
